### ISSUE TITLE
Way to high usage (Bug probably)

### ISSUE THREAD

**Issue by Henrik-3** [davizeragod/davizeragod.github.io#1]
There is (maybe) an Bug where the time between requests is around 0.2 seconds which is way to much and hits my API to hard.
![image](https://user-images.githubusercontent.com/43936184/213268124-ff570ee3-7246-45f8-8d31-a63c3894428a.png)

The URL is banned until it fixed to prevent issues on the API for everyone.

**Comment by davizeragod** [comment]
Thanks for the heads up! I probably left it to test and forgot to delete it, it was sending the request until it got code 200, now it will make a single request only.

It should be fixed now! But maybe some of its users will need to reload the page for it to update. Sorry for the problems caused!

**Comment by davizeragod** [comment]
Closing this as it should be fixed now.
